In [1]:
import numpy as np

In [2]:
onedarray=np.array([1,3,4,5])
print(onedarray)

[1 3 4 5]


In [3]:
twodarray=np.array([[3,4,5,6],[5,7,8,9]])
print(twodarray)

[[3 4 5 6]
 [5 7 8 9]]


In [4]:
thrdarray=np.array([[1,2,3,4],[3,4,5,6],[2,3,4,5]])
print(thrdarray)

[[1 2 3 4]
 [3 4 5 6]
 [2 3 4 5]]


In [5]:
print(onedarray.data)

In [6]:
print(twodarray.data)

In [7]:
print(thrdarray.data)

In [8]:
print(onedarray.shape)

(4,)


In [9]:
print(thrdarray.shape)

(3, 4)


In [10]:
print(twodarray.shape)

(2, 4)


In [11]:
print(onedarray.dtype)
print(twodarray.dtype)
print(thrdarray.dtype)

int64
int64
int64


In [12]:
print(onedarray.strides)
print(twodarray.strides)
print(thrdarray.strides)

(8,)
(32, 8)
(32, 8)


In [13]:
ones=np.ones((6,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
zero=np.zeros((6,2))
print(zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
print(ones+zero)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
np.random.random((3,3))

array([[0.20270031, 0.66983931, 0.29236426],
       [0.98877335, 0.89048295, 0.481203  ],
       [0.61974816, 0.2580805 , 0.07179984]])

In [17]:
empty=np.empty((3,2))
print(empty)

[[2.0124835e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


In [18]:
full=np.full((6,2),99)
print(full)

[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [19]:
rem= np.full((6,2),2)
print(rem)

[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


In [20]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
np.add(full,ones)

array([[100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.]])

In [23]:
np.subtract(full,ones)

array([[98., 98.],
       [98., 98.],
       [98., 98.],
       [98., 98.],
       [98., 98.],
       [98., 98.]])

In [24]:
np.multiply(full,ones)

array([[99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.]])

In [25]:
np.divide(full,ones)

array([[99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.]])

In [26]:
np.remainder(rem,full)

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [27]:
print(onedarray[0:3])

[1 3 4]


In [28]:
grt=(onedarray>=2)
print(grt)

[False  True  True  True]


In [29]:
print(twodarray[0:3,0:2])

[[3 4]
 [5 7]]
